# Generated by Django 3.1.2 on 2020-10-26 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='budgets',
            new_name='budget',
        ),
    ]
